### ISSUE TITLE
[docs] add gitlab script to docs

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#189]
see #185 

```yml
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
```

can add  `rm` commands if don't want specific files in the public folder (see also #185). This works fine: http://tlienart.gitlab.io/
