### ISSUE TITLE
Netlify Support

### ISSUE THREAD

**Issue by Nosferican** [tlienart/JuDoc.jl#208]
Thanks for putting up this project! I am taking a look at it and contemplating migrating from Hugo to JuDoc since my needs aren't too crazy. I was wondering if it was possible or work towards having JuDoc [Netlify](https://www.netlify.com/) compatible. My current personal website is [here](https://github.com/Nosferican/jbsc). I would like to keep the domain name the same as I already got my business cards printed with it 😜.

[List](https://github.com/netlify/staticgen) of SSG supported by Netlify.

Netlify Discourse [post](https://community.netlify.com/t/adding-a-new-ssg-judoc-jl/3229).

**Comment by tlienart** [comment]
Hello @Nosferican, great! (and thanks for asking on their forum, I'll be glad to see the answer)

With respect to Netlify, I'm not familiar with it so I had a look at [this tutorial](https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/) and it seems that there's no specific step needed (but I may be wrong) given that it directly connects into the github repo that contains your site (?)

So it seems like you would just have to:

1. authorize Netlify to connect to your repo (as per tutorial)
2. that's it

JuDoc produces a static website that is displayable by Github directly so I would think that when Netlify connects to the repo it just hosts it as GitHub would (but with your url). 

Could you give it a shot and let me know if you encounter snags? I'll be glad to update the docs to reflect any issues :-) 

PS: I see that you're using the Academic theme from Hugo; I've not yet ported that theme to JuDocTemplates (https://tlienart.github.io/JuDocTemplates.jl/) but you could still use it if you're willing to tweak things a bit (see [this part of the docs](https://tlienart.github.io/JuDoc.jl/dev/man/themes/#Adapting-a-theme-to-JuDoc-1)) ; I'll be happy to give you a hand if that's what you'd like to try and once we're happy with the result we can add the theme to the list :-) more generally if you need help getting started, I'll be happy to lend a hand.

Cheers

**Comment by Nosferican** [comment]
[Answer](https://community.netlify.com/t/adding-a-new-ssg-judoc-jl/3229/2?u=nosferican) to the post. It should just require adding Julia to the build image (and testing).

**Comment by tlienart** [comment]
Hmm but there's something I don't get here: why would they need to run anything? basically everything is run on your computer. Once the HTML etc is generated, the only thing they (or any other host) has to do is to serve the stuff. So they definitely do not need Julia?

I mean for my site for instance, GitHub certainly doesn't run any julia code in order to serve it 🙂 ; am I missing something?

**Comment by Nosferican** [comment]
For example, when hosting documentation through Documenter, the code is run through the continuous integration (same as the code coverage). For example,
```
# For learning how to customize the CI check out
# Continous Integration:
# https://docs.travis-ci.com/user/languages/julia
# https://github.com/marketplace/travis-ci
# Code Coverage:
# https://github.com/JuliaCI/Coverage.jl
# Documentation:
# https://github.com/JuliaDocs/Documenter.jl

language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - nightly
codecov: true
notifications:
  email: false
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: windows
      arch: x86
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.2
    - os: windows
      arch: x86
      julia: nightly
    - stage: "Documentation"
      os: linux
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
```
which then the build directory is pushed to the gh-pages branch.
Netlify does the same thing. An alternative would be to run it locally and manually push the site to a branch which Netlify then reads without having to do a build stage.
