### ISSUE TITLE
[needs docs] Can you style footnote text? 

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#243]
I can’t work out how to CSS-style the text in a footnote...

**Comment by tlienart** [comment]
Yes yes you can

### References

For the reference basically a footnote is inserted as

```html
<sup id="fnref:1"><a href="/pub/menu1.html#fndef:1" class="fnref">[1]</a></sup>
```
So you can style that with `.jd_content sup a.fnref` or some appropriate combination thereof. 

### Definitions

For definitions, it's inserted as a table like:

```html
<table class="fndef" id="fndef:blah">
    <tr>
        <td class="fndef-backref"><a href="/pub/menu1.html#fnref:blah">[2]</a></td>
        <td class="fndef-content">this is another footnote</td>
    </tr>
</table>
```

so you can style the back-reference via the `.jd-content fndef td.fndef-backref` and the text of the definition via `.jd-content fndef td.fndef-content`; consider the following base styling:

```css
.jd-content table.fndef  {
    margin: 0;
    margin-bottom: 10px;}
.jd-content .fndef tr, td {
    padding: 0;
    border: 0;
    text-align: left;}
.jd-content .fndef tr {
    border-left: 2px solid lightgray;
    }
.jd-content .fndef td.fndef-backref {
    vertical-align: top;
    font-size: 70%;
    padding-left: 5px;}
.jd-content .fndef td.fndef-content {
    font-size: 80%;
    padding-left: 10px;}
```

hope this helps!
